apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: debezium/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: LOG_LEVEL
              value: "WARN"
            - name: SERVER_ID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      restartPolicy: Always
      containers:
        - name: kafka
          image: debezium/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "1"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "209715204" # 10Mb
            - name: LOG_LEVEL
              value: "WARN"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emarket-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emarket-kafka-ui
  template:
    metadata:
      labels:
        app: emarket-kafka-ui
    spec:
      restartPolicy: Always
      containers:
        - name: emarket-kafka-ui
          image: tchiotludo/akhq:0.24.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    emarket-kafka:
                      properties:
                        bootstrap.servers: "kafka:9092"
                  ui-options:
                    topic-data:
                      sort: NEWEST
---
apiVersion: v1
kind: Service
metadata:
  name: emarket-kafka-ui
  labels:
    app: emarket-kafka-ui
spec:
  type: NodePort
  selector:
    app: emarket-kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32766